// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2016-07-08 17:28:43 UTC
//   on: 2016-08-08, 17:19:17 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Gmail API (gmail/v1)
// Generated from:
//   Version: v1
//   Revision: 48
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_GMAIL_API_AUTO_FORWARDING_H_
#define  GOOGLE_GMAIL_API_AUTO_FORWARDING_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_gmail_api {
using namespace googleapis;

/**
 * Auto-forwarding settings for an account.
 *
 * @ingroup DataObject
 */
class AutoForwarding : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static AutoForwarding* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AutoForwarding(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AutoForwarding(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~AutoForwarding();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_gmail_api::AutoForwarding</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_gmail_api::AutoForwarding");
  }

  /**
   * Determine if the '<code>disposition</code>' attribute was set.
   *
   * @return true if the '<code>disposition</code>' attribute was set.
   */
  bool has_disposition() const {
    return Storage().isMember("disposition");
  }

  /**
   * Clears the '<code>disposition</code>' attribute.
   */
  void clear_disposition() {
    MutableStorage()->removeMember("disposition");
  }


  /**
   * Get the value of the '<code>disposition</code>' attribute.
   */
  const StringPiece get_disposition() const {
    const Json::Value& v = Storage("disposition");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>disposition</code>' attribute.
   *
   * The state that a message should be left in after it has been forwarded.
   *
   * @param[in] value The new value.
   */
  void set_disposition(const StringPiece& value) {
    *MutableStorage("disposition") = value.data();
  }

  /**
   * Determine if the '<code>emailAddress</code>' attribute was set.
   *
   * @return true if the '<code>emailAddress</code>' attribute was set.
   */
  bool has_email_address() const {
    return Storage().isMember("emailAddress");
  }

  /**
   * Clears the '<code>emailAddress</code>' attribute.
   */
  void clear_email_address() {
    MutableStorage()->removeMember("emailAddress");
  }


  /**
   * Get the value of the '<code>emailAddress</code>' attribute.
   */
  const StringPiece get_email_address() const {
    const Json::Value& v = Storage("emailAddress");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>emailAddress</code>' attribute.
   *
   * Email address to which all incoming messages are forwarded. This email
   * address must be a verified member of the forwarding addresses.
   *
   * @param[in] value The new value.
   */
  void set_email_address(const StringPiece& value) {
    *MutableStorage("emailAddress") = value.data();
  }

  /**
   * Determine if the '<code>enabled</code>' attribute was set.
   *
   * @return true if the '<code>enabled</code>' attribute was set.
   */
  bool has_enabled() const {
    return Storage().isMember("enabled");
  }

  /**
   * Clears the '<code>enabled</code>' attribute.
   */
  void clear_enabled() {
    MutableStorage()->removeMember("enabled");
  }


  /**
   * Get the value of the '<code>enabled</code>' attribute.
   */
  bool get_enabled() const {
    const Json::Value& storage = Storage("enabled");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>enabled</code>' attribute.
   *
   * Whether all incoming mail is automatically forwarded to another address.
   *
   * @param[in] value The new value.
   */
  void set_enabled(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("enabled"));
  }

 private:
  void operator=(const AutoForwarding&);
};  // AutoForwarding
}  // namespace google_gmail_api
#endif  // GOOGLE_GMAIL_API_AUTO_FORWARDING_H_
