// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2016-07-08 17:28:43 UTC
//   on: 2016-08-08, 17:19:17 UTC
//   C++ generator version: 0.1.4

#ifndef  GOOGLE_GMAIL_API_GMAIL_API_H_
#define  GOOGLE_GMAIL_API_GMAIL_API_H_

#include "google/gmail_api/auto_forwarding.h"
#include "google/gmail_api/batch_delete_messages_request.h"
#include "google/gmail_api/message_part_body.h"
#include "google/gmail_api/message_part_header.h"
#include "google/gmail_api/message_part.h"
#include "google/gmail_api/message.h"
#include "google/gmail_api/draft.h"
#include "google/gmail_api/filter_action.h"
#include "google/gmail_api/filter_criteria.h"
#include "google/gmail_api/filter.h"
#include "google/gmail_api/forwarding_address.h"
#include "google/gmail_api/history_label_added.h"
#include "google/gmail_api/history_label_removed.h"
#include "google/gmail_api/history_message_added.h"
#include "google/gmail_api/history_message_deleted.h"
#include "google/gmail_api/history.h"
#include "google/gmail_api/imap_settings.h"
#include "google/gmail_api/label.h"
#include "google/gmail_api/list_drafts_response.h"
#include "google/gmail_api/list_filters_response.h"
#include "google/gmail_api/list_forwarding_addresses_response.h"
#include "google/gmail_api/list_history_response.h"
#include "google/gmail_api/list_labels_response.h"
#include "google/gmail_api/list_messages_response.h"
#include "google/gmail_api/smtp_msa.h"
#include "google/gmail_api/send_as.h"
#include "google/gmail_api/list_send_as_response.h"
#include "google/gmail_api/thread.h"
#include "google/gmail_api/list_threads_response.h"
#include "google/gmail_api/modify_message_request.h"
#include "google/gmail_api/modify_thread_request.h"
#include "google/gmail_api/pop_settings.h"
#include "google/gmail_api/profile.h"
#include "google/gmail_api/vacation_settings.h"
#include "google/gmail_api/watch_request.h"
#include "google/gmail_api/watch_response.h"

#include "google/gmail_api/gmail_service.h"


#endif  // GOOGLE_GMAIL_API_GMAIL_API_H_
