// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2016-07-08 17:28:43 UTC
//   on: 2016-08-08, 17:19:17 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Gmail API (gmail/v1)
// Generated from:
//   Version: v1
//   Revision: 48
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_GMAIL_API_LIST_FORWARDING_ADDRESSES_RESPONSE_H_
#define  GOOGLE_GMAIL_API_LIST_FORWARDING_ADDRESSES_RESPONSE_H_

#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/gmail_api/forwarding_address.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_gmail_api {
using namespace googleapis;

/**
 * Response for the ListForwardingAddresses method.
 *
 * @ingroup DataObject
 */
class ListForwardingAddressesResponse : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ListForwardingAddressesResponse* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ListForwardingAddressesResponse(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ListForwardingAddressesResponse(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ListForwardingAddressesResponse();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_gmail_api::ListForwardingAddressesResponse</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_gmail_api::ListForwardingAddressesResponse");
  }

  /**
   * Determine if the '<code>forwardingAddresses</code>' attribute was set.
   *
   * @return true if the '<code>forwardingAddresses</code>' attribute was set.
   */
  bool has_forwarding_addresses() const {
    return Storage().isMember("forwardingAddresses");
  }

  /**
   * Clears the '<code>forwardingAddresses</code>' attribute.
   */
  void clear_forwarding_addresses() {
    MutableStorage()->removeMember("forwardingAddresses");
  }


  /**
   * Get a reference to the value of the '<code>forwardingAddresses</code>'
   * attribute.
   */
  const client::JsonCppArray<ForwardingAddress > get_forwarding_addresses() const;

  /**
   * Gets a reference to a mutable value of the
   * '<code>forwardingAddresses</code>' property.
   *
   * List of addresses that may be used for forwarding.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<ForwardingAddress > mutable_forwardingAddresses();

 private:
  void operator=(const ListForwardingAddressesResponse&);
};  // ListForwardingAddressesResponse
}  // namespace google_gmail_api
#endif  // GOOGLE_GMAIL_API_LIST_FORWARDING_ADDRESSES_RESPONSE_H_
