// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2016-07-08 17:28:43 UTC
//   on: 2016-08-08, 17:19:17 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Gmail API (gmail/v1)
// Generated from:
//   Version: v1
//   Revision: 48
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_GMAIL_API_POP_SETTINGS_H_
#define  GOOGLE_GMAIL_API_POP_SETTINGS_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_gmail_api {
using namespace googleapis;

/**
 * POP settings for an account.
 *
 * @ingroup DataObject
 */
class PopSettings : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static PopSettings* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PopSettings(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PopSettings(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~PopSettings();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_gmail_api::PopSettings</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_gmail_api::PopSettings");
  }

  /**
   * Determine if the '<code>accessWindow</code>' attribute was set.
   *
   * @return true if the '<code>accessWindow</code>' attribute was set.
   */
  bool has_access_window() const {
    return Storage().isMember("accessWindow");
  }

  /**
   * Clears the '<code>accessWindow</code>' attribute.
   */
  void clear_access_window() {
    MutableStorage()->removeMember("accessWindow");
  }


  /**
   * Get the value of the '<code>accessWindow</code>' attribute.
   */
  const StringPiece get_access_window() const {
    const Json::Value& v = Storage("accessWindow");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>accessWindow</code>' attribute.
   *
   * The range of messages which are accessible via POP.
   *
   * @param[in] value The new value.
   */
  void set_access_window(const StringPiece& value) {
    *MutableStorage("accessWindow") = value.data();
  }

  /**
   * Determine if the '<code>disposition</code>' attribute was set.
   *
   * @return true if the '<code>disposition</code>' attribute was set.
   */
  bool has_disposition() const {
    return Storage().isMember("disposition");
  }

  /**
   * Clears the '<code>disposition</code>' attribute.
   */
  void clear_disposition() {
    MutableStorage()->removeMember("disposition");
  }


  /**
   * Get the value of the '<code>disposition</code>' attribute.
   */
  const StringPiece get_disposition() const {
    const Json::Value& v = Storage("disposition");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>disposition</code>' attribute.
   *
   * The action that will be executed on a message after it has been fetched via
   * POP.
   *
   * @param[in] value The new value.
   */
  void set_disposition(const StringPiece& value) {
    *MutableStorage("disposition") = value.data();
  }

 private:
  void operator=(const PopSettings&);
};  // PopSettings
}  // namespace google_gmail_api
#endif  // GOOGLE_GMAIL_API_POP_SETTINGS_H_
