// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2016-07-08 17:28:43 UTC
//   on: 2016-08-08, 17:19:17 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Gmail API (gmail/v1)
// Generated from:
//   Version: v1
//   Revision: 48
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_GMAIL_API_SMTP_MSA_H_
#define  GOOGLE_GMAIL_API_SMTP_MSA_H_

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_gmail_api {
using namespace googleapis;

/**
 * Configuration for communication with an SMTP service.
 *
 * @ingroup DataObject
 */
class SmtpMsa : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static SmtpMsa* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit SmtpMsa(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit SmtpMsa(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~SmtpMsa();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_gmail_api::SmtpMsa</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_gmail_api::SmtpMsa");
  }

  /**
   * Determine if the '<code>host</code>' attribute was set.
   *
   * @return true if the '<code>host</code>' attribute was set.
   */
  bool has_host() const {
    return Storage().isMember("host");
  }

  /**
   * Clears the '<code>host</code>' attribute.
   */
  void clear_host() {
    MutableStorage()->removeMember("host");
  }


  /**
   * Get the value of the '<code>host</code>' attribute.
   */
  const StringPiece get_host() const {
    const Json::Value& v = Storage("host");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>host</code>' attribute.
   *
   * The hostname of the SMTP service. Required.
   *
   * @param[in] value The new value.
   */
  void set_host(const StringPiece& value) {
    *MutableStorage("host") = value.data();
  }

  /**
   * Determine if the '<code>password</code>' attribute was set.
   *
   * @return true if the '<code>password</code>' attribute was set.
   */
  bool has_password() const {
    return Storage().isMember("password");
  }

  /**
   * Clears the '<code>password</code>' attribute.
   */
  void clear_password() {
    MutableStorage()->removeMember("password");
  }


  /**
   * Get the value of the '<code>password</code>' attribute.
   */
  const StringPiece get_password() const {
    const Json::Value& v = Storage("password");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>password</code>' attribute.
   *
   * The password that will be used for authentication with the SMTP service.
   * This is a write-only field that can be specified in requests to create or
   * update SendAs settings; it is never populated in responses.
   *
   * @param[in] value The new value.
   */
  void set_password(const StringPiece& value) {
    *MutableStorage("password") = value.data();
  }

  /**
   * Determine if the '<code>port</code>' attribute was set.
   *
   * @return true if the '<code>port</code>' attribute was set.
   */
  bool has_port() const {
    return Storage().isMember("port");
  }

  /**
   * Clears the '<code>port</code>' attribute.
   */
  void clear_port() {
    MutableStorage()->removeMember("port");
  }


  /**
   * Get the value of the '<code>port</code>' attribute.
   */
  int32 get_port() const {
    const Json::Value& storage = Storage("port");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>port</code>' attribute.
   *
   * The port of the SMTP service. Required.
   *
   * @param[in] value The new value.
   */
  void set_port(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("port"));
  }

  /**
   * Determine if the '<code>securityMode</code>' attribute was set.
   *
   * @return true if the '<code>securityMode</code>' attribute was set.
   */
  bool has_security_mode() const {
    return Storage().isMember("securityMode");
  }

  /**
   * Clears the '<code>securityMode</code>' attribute.
   */
  void clear_security_mode() {
    MutableStorage()->removeMember("securityMode");
  }


  /**
   * Get the value of the '<code>securityMode</code>' attribute.
   */
  const StringPiece get_security_mode() const {
    const Json::Value& v = Storage("securityMode");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>securityMode</code>' attribute.
   *
   * The protocol that will be used to secure communication with the SMTP
   * service. Required.
   *
   * @param[in] value The new value.
   */
  void set_security_mode(const StringPiece& value) {
    *MutableStorage("securityMode") = value.data();
  }

  /**
   * Determine if the '<code>username</code>' attribute was set.
   *
   * @return true if the '<code>username</code>' attribute was set.
   */
  bool has_username() const {
    return Storage().isMember("username");
  }

  /**
   * Clears the '<code>username</code>' attribute.
   */
  void clear_username() {
    MutableStorage()->removeMember("username");
  }


  /**
   * Get the value of the '<code>username</code>' attribute.
   */
  const StringPiece get_username() const {
    const Json::Value& v = Storage("username");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>username</code>' attribute.
   *
   * The username that will be used for authentication with the SMTP service.
   * This is a write-only field that can be specified in requests to create or
   * update SendAs settings; it is never populated in responses.
   *
   * @param[in] value The new value.
   */
  void set_username(const StringPiece& value) {
    *MutableStorage("username") = value.data();
  }

 private:
  void operator=(const SmtpMsa&);
};  // SmtpMsa
}  // namespace google_gmail_api
#endif  // GOOGLE_GMAIL_API_SMTP_MSA_H_
